language: go
go:
  - 1.12.x

go_import_path: github.com/YukiMiyatake/GOSICK

sudo: required
env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose up -d

install:

before_script:

script:
  - scripts/docker_app_test
 # - docker-compose exec golang go test -v ./...

after_script:

notifications:
