version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    image: gosick-app
    container_name: gosick-app
#    tty: true
    volumes:
      - ./src:/src
    links:
      - redis

  redis:
    build:
      context: .
      dockerfile: Dockerfile_redis
#    image: gosick-redis
    container_name: gosick-redis
    command: redis-server --appendonly yes
    volumes:
       - ./volume/redis:/data
