FROM golang:1.12.7-alpine3.10

#ENV GOBIN=$GOPATH/bin
WORKDIR /aws
RUN mkdir /root/.aws
COPY .credentials /root/.aws/
RUN apk add --no-cache git gcc musl-dev
RUN \
	mkdir -p /aws && \
	apk -Uuv add groff less python py-pip redis && \
	pip install awscli && \
	apk --purge -v del py-pip && \
	rm /var/cache/apk/*


WORKDIR /build
COPY src .
CMD [./build.sh]


WORKDIR /app
COPY /build/GOSICK .
CMD rmdir /build
CMD [GOSICK]

